version: '2'
services:
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
  todo-api: 
    image: frifos/dc-todo-api:latest
    ports: 
        - "3100:3000" # expose port 3100 to outside containers
    depends_on:
        - mongo # Wait for mongo-service to be started before starting this container
    environment:
        - PORT=3000
        - DATABASE_URL=mongodb://mongo/db # Mongo db is available on host 'mongo' in this private network.
  user-api: 
    image: frifos/dc-user-api:v2.5
    ports: 
        - "3200:3000" # expose port 3200 to outside containers
    depends_on:
        - mongo # Wait for mongo-service to be started before starting this container
    environment:
        - PORT=3000
        - DATABASE_URL=mongodb://mongo/db # Mongo db is available on host 'mongo' in this private network.
  coffee-api: 
    image: frifos/dc-coffee-api:v1.0.3
    ports: 
        - "3300:3000" # expose port 3300 to outside containers
    depends_on:
        - mongo # Wait for mongo-service to be started before starting this container
    environment:
        - PORT=3000
        - DATABASE_URL=mongodb://mongo/db # Mongo db is available on host 'mongo' in this private network.
